name: nova_commerce

description: "Nova Commerce is a production-ready mobile commerce application built with Flutter and Firebase, featuring real-time product management, secure checkout, orders, authentication, and an AI assistant. Designed with performance, scalability, and modern UX best practices"

publish_to: 'none'

version: 1.0.0+1



environment:

  sdk: ^3.8.1

dependencies:

  flutter:

    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.6.1

  go_router: ^14.8.1

  shared_preferences: ^2.3.5

  firebase_core: ^3.15.0

  cloud_firestore: ^5.6.0

  firebase_auth: ^5.6.0

  google_sign_in: ^6.2.2

  cached_network_image: ^3.3.1

  flutter_screenutil: ^5.9.3

  uuid: ^4.5.1

  flutter_secure_storage: ^9.2.2

  phone_number: ^2.1.0

  country_picker: ^2.0.26

  http: ^1.2.2

  meta: ^1.16.0

  hive: ^2.2.3

  hive_flutter: ^1.1.0

  tflite_flutter: ^0.11.0



dev_dependencies:

  flutter_test:

    sdk: flutter

  fake_async: ^1.3.1

  flutter_launcher_icons: ^0.14.2


  flutter_lints: ^5.0.0



flutter_icons:

  android: true

  ios: true

  image_path: assets/images/nova.png

flutter:

  uses-material-design: true

  assets:

    - assets/screenshots/

    - assets/images/

    - assets/models/ai_nav_model_quant.tflite


  fonts:

    - family: Inter

      fonts:

        - asset: assets/fonts/Inter-Regular.ttf

          weight: 400

        - asset: assets/fonts/Inter-Medium.ttf

          weight: 500

        - asset: assets/fonts/Inter-SemiBold.ttf

          weight: 600

        - asset: assets/fonts/Inter-Bold.ttf

          weight: 700





